/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import React from 'react';
import { Paper, JournalArticle } from './types';

export const BRAND_NAME = 'Schroeder Technologies';

export const GLOSSARY: Record<string, string> = {
  "Algorithm": "A set of rules or instructions given to an AI to help it solve a problem or complete a task.",
  "Machine Learning": "A way for computers to learn from data without being explicitly programmed for every step.",
  "Bias": "When an AI makes unfair decisions because the data it learned from was incomplete or unfair.",
  "Deepfake": "A video or image generated by AI that looks real but is actually fake.",
  "Digital Footprint": "The trail of data you leave behind when you use the internet.",
  "Neural Network": "A computer system designed to mimic the way the human brain learns and processes information.",
  "Phishing": "A trick used by scammers to get you to reveal private information like passwords.",
  "Chatbot": "A computer program designed to simulate conversation with human users.",
  "Privacy": "The right to keep your personal information safe and secret from others.",
  "Misinformation": "False or inaccurate information that is spread, regardless of whether there is an intent to deceive.",
  "Prompt": "The text input you give to an AI to tell it what to do.",
  "Data": "Information, facts, or numbers that computers use to learn and make decisions."
};

export const JOURNAL_ARTICLES: JournalArticle[] = [
  {
    id: 1,
    title: 'Why AI Needs "Data Nutrition Labels"',
    date: 'Current Issue',
    excerpt: 'Just like food, we need to know what goes into the AI models we use. Understanding data quality helps us spot bias.',
    content: React.createElement('p', null, 'Before trusting an AI, we must ask: Where did it learn this? "Data Nutrition Labels" are a proposed standard to show the ingredients of a dataset, helping students and teachers identify potential biases and gaps in knowledge.')
  },
  {
    id: 2,
    title: 'The Great Deepfake Detective',
    date: 'Safety Guide',
    excerpt: 'How to spot AI-generated images and videos in your social feed using critical thinking and visual clues.',
    content: React.createElement('p', null, 'AI is getting better at making fake images, but it often struggles with details. Look for mismatched earrings, weird hands, or text that doesn\'t make sense in the background. These "glitches" are your clues that what you are seeing might not be real.')
  }
];

// Helper for ticker symbols/logos -> Now "Topics"
export const getPublisherInfo = (publisher: string) => {
    // Map publishers (Topics) to colors/styles
    const map: Record<string, { logo: string, desc: string, color: string }> = {
       "Logic": { logo: "LO", desc: "Critical Thinking", color: "#F7931A" },
       "Safety": { logo: "SA", desc: "Online Safety", color: "#627EEA" },
       "Data": { logo: "DA", desc: "Data Literacy", color: "#14F195" },
       "Ethics": { logo: "ET", desc: "AI Ethics", color: "#0033AD" },
       "Create": { logo: "CR", desc: "Creative AI", color: "#E6007A" },
       "Social": { logo: "SO", desc: "Social Media", color: "#23292F" },
       "Future": { logo: "FU", desc: "Future Skills", color: "#C2A633" },
       "Code": { logo: "CO", desc: "Coding Basics", color: "#2775CA" },
       "Bot": { logo: "BO", desc: "Robotics", color: "#2A5ADA" },
       "Check": { logo: "CH", desc: "Fact Checking", color: "#8247E5" }
    };

    return map[publisher] || { 
        logo: publisher.substring(0, 2).toUpperCase(), 
        desc: "General Knowledge",
        color: "#6A4FBF"
    };
};

const MODULE_DATA = [
  {
    id: "mod-001",
    title: "Understanding AI",
    publisher: "Logic",
    year: "Module 1",
    field: "Foundations",
    link: "#",
    description: "What actually is AI? Students explore the 'Laboratory' to see the difference between traditional code and machine learning through interactive experiments.",
    insights: ["Definitions", "Machine Learning", "Intelligence"],
    whyMatters: "Demystifies the technology they use every day.",
    authors: ["Schroeder Core"],
    readTime: "Basic"
  },
  {
    id: "mod-002",
    title: "Data & Patterns",
    publisher: "Data",
    year: "Module 2",
    field: "Logic",
    link: "#",
    description: "Enter the 'Data Garden'. Students visually explore how computers find patterns in chaos by touching, dragging, and sorting data sets.",
    insights: ["Pattern Recognition", "Datasets", "Sorting"],
    whyMatters: "Teaches that AI is only as good as the data it is fed.",
    authors: ["Data Lab"],
    readTime: "Core"
  },
  {
    id: "mod-003",
    title: "Misinformation",
    publisher: "Check",
    year: "Module 4",
    field: "Trust",
    link: "#",
    description: "Step into the 'Newsroom'. Students act as fact-checkers, spotting deepfakes and verifying sources before publishing stories.",
    insights: ["Deepfakes", "Fact Checking", "Sources"],
    whyMatters: "Critical for navigating modern social media feeds.",
    authors: ["Fact Squad"],
    readTime: "Critical"
  },
  {
    id: "mod-004",
    title: "Bias Awareness",
    publisher: "Ethics",
    year: "Module 5",
    field: "Fairness",
    link: "#",
    description: "Visit the 'Mirror Room'. Students see how incomplete data leads to unfair outcomes and learn how to train fairer models.",
    insights: ["Fairness", "Inclusion", "Stereotypes"],
    whyMatters: "Ensures the next generation builds inclusive technology.",
    authors: ["Ethics Lab"],
    readTime: "Advanced"
  },
  {
    id: "mod-005",
    title: "Digital Citizenship",
    publisher: "Social",
    year: "Module 6",
    field: "Society",
    link: "#",
    description: "Walk through the 'City'. Real-life scenarios challenge students to make respectful, safe, and responsible decisions online.",
    insights: ["Respect", "Cyberbullying", "Empathy"],
    whyMatters: "Cultivates positive online behavior and community.",
    authors: ["Civics AI"],
    readTime: "Core"
  },
  {
    id: "mod-006",
    title: "Privacy & Safety",
    publisher: "Safety",
    year: "Module 7",
    field: "Security",
    link: "#",
    description: "Defend the 'Fortress'. A tower defense game where students protect their digital footprint using strong passwords and privacy settings.",
    insights: ["Passwords", "Data Privacy", "Digital Footprint"],
    whyMatters: " Essential self-protection skills for the connected world.",
    authors: ["Safety First"],
    readTime: "Critical"
  }
];

export const PAPERS: Paper[] = MODULE_DATA.map(item => ({
    id: item.id,
    title: item.title,
    publisher: item.publisher,
    authors: item.authors,
    abstractPreview: item.description,
    abstract: item.description,
    publicationDate: String(item.year),
    category: item.field, 
    doi: item.link,
    whyMatters: item.whyMatters,
    upvotes: Math.floor(Math.random() * 500) + 100, // XP Points
    timestamp: Date.now(), 
    aiInsights: item.insights,
    industry: [item.field],
    readTime: item.readTime, // Difficulty Level
    publisherLogo: getPublisherInfo(item.publisher).logo
    // fileUrl removed
}));